name: CI

on:
  push:
    paths:
      - 'projects/ngx-fragments/src/**/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"

      # Build
      - run: yarn install
      - run: yarn test
      - run: yarn release
      - run: yarn build

      # Publish
      - run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Push release to GH tag
      - run: git push --follow-tags origin main
