name: CI

on: push

jobs:
  build:
    # Name the Job
    name: Build Lib
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Runs the Super-Linter action
      - name: Install depdendencies
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Build lib
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: build
