name: GH Pages

on:
  push:
    paths:
      - 'src/**/*'
      - 'package.json'
jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"

      # Install dependencies
      - run: yarn install

      # Deploy GH Pages
      - run: yarn deploy-gh-pages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
